# Generated by Django 3.0.4 on 2020-06-05 15:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 15, 13, 31, 429604, tzinfo=utc), verbose_name='timestamp')),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_other_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=450, null=True, verbose_name='message')),
                ('image', models.FileField(null=True, upload_to='', verbose_name='file')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 15, 13, 31, 429604, tzinfo=utc), verbose_name='timestamp')),
                ('seen', models.BooleanField(default=False, verbose_name='seen')),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='chat.ChatUser')),
            ],
        ),
    ]
