# Generated by Django 3.0.4 on 2020-06-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200605_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reciever',
            field=models.CharField(default='vipin', max_length=350, verbose_name='reciever'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(default='vipin_s0106', max_length=350, verbose_name='sender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatuser',
            name='unseen_message_count',
            field=models.IntegerField(default=0, verbose_name='unseen_message_count'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
