# Generated by Django 3.0.4 on 2020-06-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200606_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='reciever',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver',
            field=models.CharField(default='vipin', max_length=350, verbose_name='receiver'),
            preserve_default=False,
        ),
    ]
