# Generated by Django 3.0.4 on 2020-06-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200606_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
