# Generated by Django 3.0.4 on 2020-06-18 14:01

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200613_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=chat.models.upload_user_chat_img_gif, verbose_name='image'),
        ),
    ]
