# Generated by Django 3.0.4 on 2020-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_other_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='message'),
        ),
    ]
