# Generated by Django 3.0.4 on 2020-05-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20200525_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('unfollow', 'unfollow'), ('like', 'like'), ('comment', 'comment'), ('request_accepted', 'request_accepted')], max_length=300, verbose_name='notification_type'),
        ),
    ]
