# Generated by Django 3.0.4 on 2020-06-12 18:56

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200426_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=user.models.upload_user_profile_path, verbose_name='background_picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=user.models.upload_user_profile_path, verbose_name='profile_picture'),
        ),
    ]
