# Generated by Django 3.0.4 on 2020-04-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='comment')),
                ('like', models.BooleanField(blank=True, null=True, verbose_name='like')),
                ('post_action_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='post_action_timestamp')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_detail', to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
