# Generated by Django 3.0.4 on 2020-06-12 18:55

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200426_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(max_length=500, upload_to=post.models.upload_user_post_path, verbose_name='file'),
        ),
    ]
